### ISSUE TITLE
PHPMyAdmin not found (404) while its container is running

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/RAP#100]
#### Situation
I wanted to look into the RAP4 database using PHPMyAdmin

#### What did you expect would happen?
I expected that I could login into PHPMyAdmin.

#### Steps to reproduce this
1. I verified that PHPMyAdmin is running by means of `docker ps`
```
sjo@lnx-hrl-202v:~/RAP$ docker ps
CONTAINER ID        IMAGE                                COMMAND                  CREATED             STATUS              PORTS                                      NAMES
e4746a92698c        phpmyadmin/phpmyadmin:latest         "/docker-entrypoint.…"   35 hours ago        Up 35 hours         80/tcp                                     phpmyadmin
cf2860cca49e        ampersandtarski/enroll:latest        "docker-php-entrypoi…"   35 hours ago        Up 35 hours         80/tcp                                     enroll
2e151c4d198d        ampersandtarski/ampersand-rap:2020   "docker-php-entrypoi…"   35 hours ago        Up 35 hours         80/tcp                                     rap4
f1148202b670        mariadb:10.4                         "docker-entrypoint.s…"   35 hours ago        Up 35 hours         3306/tcp                                   rap4-db
05827641360c        traefik:v2.2                         "/entrypoint.sh trae…"   35 hours ago        Up 35 hours         0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   traefik
```
2. I went to the login screen of PHPMyAdmin by means of the URL `phpmyadmin.rap.cs.ou.nl`
![afbeelding](https://user-images.githubusercontent.com/275768/100919372-01a46d00-34da-11eb-8536-c662e3f4a53d.png)

**Comment by stefjoosten** [comment]
## Analysis
I looked at the Traefik log looking for a clue. The actions above have added two lines to the log:
```
traefik                    | time="2020-12-02T19:00:51Z" level=error msg="field not found, node: enroll" container=phpmyadmin-rap-e4746a92698c47da166162af9b2602da420501239272840190df299839081e59 providerName=docker
traefik                    | time="2020-12-02T19:00:52Z" level=error msg="field not found, node: enroll" container=phpmyadmin-rap-e4746a92698c47da166162af9b2602da420501239272840190df299839081e59 providerName=docker
```
There is something peculiar about this because the log lines relate the node `enroll` with the `phpmyadmin` container. The `docker-compose.yml` file does not relate these two in any way, so I don't understand these log lines. Neither does it inspire my diagnosis.

The specification of this container in `docker-compose.yml` is:
```
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db # refers to database service above
    container_name: phpmyadmin
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.phpmyadmin-insecure.rule: Host(`phpmyadmin.${SERVER_HOST_NAME}`)
    depends_on:
      - db
      - traefik
    networks:
      - proxy
      - db
```
This is extended in `docker-compose.prod.yml` by:
```
  phpmyadmin:
    labels:
      traefik.http.routers.phpmyadmin-insecure.middlewares: redirectToHttps@file,securityHeaders@file
      traefik.http.routers.phpmyadmin.tls.certresolver: letsencrypt
      traefik.http.routers.phpmyadmin.tls.options: safeTLSOptions@file
      traefik.http.routers.phpmyadmin.middlewares: securityHeaders@file
      traefik.http.routers.phpmyadmin.enroll.rule: Host(`phpmyadmin.rap.cs.ou.nl`)
```
