### ISSUE TITLE
Configure domain names

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/RAP#239]
As discussed we'll have a couple of subdomains of `tarski.nl` available to route to the RAP / Ordina cluster.

@FreekOrdina, if you have the static IP address for the kube cluster please let us know in this issue.

@stefjoosten, you can then configure the following DNS records

| Host | Type record | Value
| ----- | ------------- | ------ |
| a-team.tarski.nl | A | `<IP address>` |
| *.a-team.tarski.nl | CNAME | a-team.tarski.nl |
| rap.tarski.nl | CNAME | a-team.tarski.nl |
| *.rap.tarski.nl | CNAME | a-team.tarski.nl |
| *.student.rap.tarski.nl | CNAME | a-team.tarski.nl |

I've introduced the subdomain `a-team`.tarski.nl for the A-team to experiment and/or host other services (next to RAP).

All configured (wildcard) domains point to the same IP address and are handled by the NGINX ingress controller in the A-team kube cluster.

Below an example of an ingress resource for a student prototype to be exposed on the domain.
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: student123-ingress
  namespace: students
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  rules:
  - host: student123.student.rap.tarski.nl
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: student123-prototype-svc
            port:
              number: 80
  tls:
  - secretName: student123-student-rap-tarski-nl
    hosts:
    - student123.student.rap.tarski.nl
```
