### ISSUE TITLE
Why does RAP need ghostscript?

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/RAP#60]
I expected to create a diagnosis file using LaTeX, by pushing the "Diagnosis"-button in the Script-interface. However, the diagnosis returned an error message.

![image](https://user-images.githubusercontent.com/275768/43316296-2b594468-9199-11e8-9a88-6427875b47b3.png)

#### Reproducing the error
1. pull RAP from docker-hub
```
docker build -t ampersandtarski/ampersand-rap:issue60 .
```
2. Create a file `docker-compose.yml` in your working directory. See below for the contents of this file.
3. Run RAP
```
docker-compose up -d
```
4. open your browser and navigate to `localhost/RAP3`
5. log in  or register
6. create a new script
7. compile it
8. create a diagnosis

#### Version of RAP
This issue occured in RAP3 with docker image 14c7a817ecbe, created July 27th 2018, the source of which resides in commit AmpersandTarski/RAP@65887e439ab77cc49e72a2e2ec8bb26bb962305b.
This image was created by Ampersand-v3.11.0 [master:d1ce3dd], build time: 27-Jul-18 06:59:47 UTC.
This can be run locally if you make a docker-compose.yml file with the following contents:
```
version: '2'

services:
  rap3:
    restart: always
    image: ampersandtarski/ampersand-rap:issue60
    ports:
      - "80:80"
    links:
      - db
    volumes:
      - ./volumes/log:/var/www/html/RAP3/log
      - ./volumes/scripts:/var/www/html/RAP3/scripts
 
  db:
    restart: always
    image: ampersandtarski/rap3-db
    volumes:
      - ./volumes/mysql:/var/lib/mysql

  phptools:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    links:
      - db

```
#### Keywords for finding this issue
```
!!! Error: Cannot open Ghostscript for piped input: gs -q -dSAFER -dNOPAUSE -dBATCH
```
